### ISSUE TITLE
Yarn install failed

### ISSUE THREAD

**Issue by robertovillarejo** [theia-ide/yangster-electron#24]
I installed:
- [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk)
- `npm install --global --production windows-build-tools` with PowerShell as administrator

Then I tried to run the project:
```
git clone https://github.com/theia-ide/yangster-electron && \
cd yangster-electron && \
yarn
```

I got the following error:
```
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
warning @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "theia-yang-extension > sprotty > snabbdom-virtualize@0.7.0" has incorrect peer dependency "snabbdom@~0.6.6".
warning "@theia/cli > @theia/application-package > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[4/4] Building fresh packages...
[7/7] ⠈ find-git-repositories
[6/7] ⠈ dugite
[3/7] ⠁ node-pty: Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador "/m".
[4/7] ⠁ nsfw: C:\Users\roberto.villarejo\git\yangster-electron\node_modules\nsfw\build\openpa\openpa.vcxproj(20,3): error MSB4019: No se encuentra el proyecto importado "C
error An unexpected error occurred: "C:\\Users\\roberto.villarejo\\git\\yangster-electron\
ode_modules\
sfw: Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\\Users\\roberto.villarejo\\git\\yangster-electron\
ode_modules\
sfw
Output:
C:\\Users\\roberto.villarejo\\git\\yangster-electron\
ode_modules\
sfw>if not defined npm_config_node_gyp (node \"C:\\Program Files\
odejs\
ode_modules\
pm\\bin\
ode-gyp-bin\\\\..\\..\
ode_modules\
ode-gyp\\bin\
ode-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | win32 | x64
gyp info spawn C:\\Users\\roberto.villarejo\\.windows-build-tools\\python27\\python.EXE
gyp info spawn args [ 'C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\roberto.villarejo\\\\git\\\\yangster-electron\\\
ode_modules\\\
sfw\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\roberto.villarejo\\\\.node-gyp\\\\8.10.0\\\\include\\\
ode\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\roberto.villarejo\\\\.node-gyp\\\\8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\roberto.villarejo\\\\.node-gyp\\\\8.10.0\\\\<(target_arch)\\\
ode.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\roberto.villarejo\\\\git\\\\yangster-electron\\\
ode_modules\\\
sfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\roberto.villarejo\\\\git\\\\yangster-electron\\\
ode_modules\\\
sfw\\\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Warning: Missing input files:
C:\\Users\\roberto.villarejo\\git\\yangster-electron\
ode_modules\
sfw\\build\\openpa\\..\\..\\openpa\\src\\primitives\\opa_nt_intrinics.h
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador \"/m\".
C:\\Users\\roberto.villarejo\\git\\yangster-electron\
ode_modules\
sfw\\build\\openpa\\openpa.vcxproj(20,3): error MSB4019: No se encuentra el proyecto importado \"C:\\Microsoft.Cpp.Default.props\". Aseg�rese de que la ruta de acceso de la declara
ci�n <Import> es correcta y de que el archivo se encuentra en el disco.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Program Files\
odejs\
ode_modules\
pm\
ode_modules\
ode-gyp\\lib\\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\Program Files\\\
odejs\\\
ode.exe\" \"C:\\\\Program Files\\\
odejs\\\
ode_modules\\\
pm\\\
ode_modules\\\
ode-gyp\\\\bin\\\
ode-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\roberto.villarejo\\git\\yangster-electron\
ode_modules\
sfw
gyp ERR! node -v v8.10.0
```

¿What am I missing?

I have installed:
```
$ node -v && npm -v && yarn -v
v8.10.0
5.6.0
1.5.1
```

**Comment by kittaakos** [comment]
I have just tried it out on my Windows 10 image, and the build succeeded.

First, please check your Python version. If that is `2.7.x`, then I would continue the investigation by setting back the `yarn` version to `1.2.1`.

I have the followings installed:
```
$ node --version && npm --version && yarn --version && python --version
v8.7.0
5.4.2
1.2.1
Python 2.7.13
```


Byt the way, may I ask, why do you want to build this locally? It does not contain any code. This is just a kind of assembler repository with tiny branding things. If you just need an executable with the latest [`Theia`](https://github.com/theia-ide/theia) code, I can release a new version.

**Comment by robertovillarejo** [comment]
I replaced my yarn with version 1.2.1 and Python is on 2.7.14 version.
```
$ node --version && npm --version && yarn --version && python --version
v8.10.0
5.6.0
1.2.1
Python 2.7.14
```
I tried to build this project and the [Theia Electron Example](https://github.com/theia-ide/theia-electron-app-example) with no success. 
Actually, I'm working on a Theia Electron App initialized with [Electron Forge](https://github.com/electron-userland/electron-forge) but I'm getting the same error. I thought it was something related to Electron Forge, that's why I came here to test this build first. 
I'm newbie in Electron.

**Comment by robertovillarejo** [comment]
Searching on the web today, I noticed that I need a env variable called VCTargetsPath with value C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140.

I also did this
```
$ npm config get msvs_version
2015
$ npm config set msvs_version 2017 --global
```
After that, I was able to build the project.
Thanks

**Comment by kittaakos** [comment]
I am glad you have managed to build it. I will update our documentation with the fix you found for the problem.
