### ISSUE TITLE
[windows] Cannot open `yang` files on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/yangster-electron#3]
```
Uncaught (in promise) A resource provider for 'file:///c%3A/Users/kittaakos/Desktop/a.yang' is not registered.
```

**Comment by kittaakos** [comment]
Works on OS X.

**Comment by kittaakos** [comment]
The problem does not happen in debug mode (Windows) either. It only occurs when opening a `yang` file in a bundled application.

**Comment by kittaakos** [comment]
I cannot reproduce it anymore. It happened at the very first start of the application right after the installation process on Windows.

**Comment by kittaakos** [comment]
It does not start on Ubuntu either. (I have bundled it into an `AppImage`, maybe that is the problem.)
```
Yang: [Info  - 2:01:23 AM] Connection to server got closed. Server will restart.
console-window.ts:17 Connection got disposed.
ConsoleWindow.showMessage @ console-window.ts:17
console-window.ts:40 Yang: [Error - 2:01:23 AM] Server initialization failed.
console-window.ts:40 Yang: Error: Connection got disposed.
    at Object.dispose (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:15023:25)
    at file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:82705:56
    at CallbackList.invoke (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14073:39)
    at Emitter.fire (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14137:36)
    at closeHandler (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14419:26)
    at CallbackList.invoke (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14073:39)
    at Emitter.fire (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14137:36)
    at WebSocketMessageReader.AbstractMessageReader.fireClose (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:19297:27)
    at WebSocketMessageReader.fireClose (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:49582:40)
    at file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:49539:19
console-window.ts:17 Connection got disposed.
ConsoleWindow.showMessage @ console-window.ts:17
console-window.ts:40 Yang: [Error - 2:01:23 AM] Server initialization failed.
console-window.ts:40 Yang: Error: Connection got disposed.
    at Object.dispose (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:15023:25)
    at file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:82705:56
    at CallbackList.invoke (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14073:39)
    at Emitter.fire (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14137:36)
    at closeHandler (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14419:26)
    at CallbackList.invoke (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14073:39)
    at Emitter.fire (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:14137:36)
    at WebSocketMessageReader.AbstractMessageReader.fireClose (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:19297:27)
    at WebSocketMessageReader.fireClose (file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:49582:40)
    at file:///tmp/.mount_yangstaXtECQ/app/resources/app/lib/bundle.js:49539:19
index.html:1 Uncaught (in promise) Error: Connection got disposed.
    at Object.dispose (main.js:825)
    at connection.ts:14
    at CallbackList.invoke (events.js:71)
    at Emitter.fire (events.js:135)
    at closeHandler (main.js:221)
    at CallbackList.invoke (events.js:71)
    at Emitter.fire (events.js:135)
    at WebSocketMessageReader.AbstractMessageReader.fireClose (messageReader.js:135)
    at WebSocketMessageReader.fireClose (reader.ts:72)
    at reader.ts:31
main.js:138 Uncaught (in promise) Error: Connection is disposed.
    at new ConnectionError (main.js:138)
    at throwIfClosedOrDisposed (main.js:616)
    at Object.sendRequest (main.js:715)
    at Object.shutdown (connection.js:20)
    at resolveConnection.then.connection (base.js:845)
    at <anonymous>
index.html:1 Uncaught (in promise) Error: Connection got disposed.
    at Object.dispose (main.js:825)
    at connection.ts:14
    at CallbackList.invoke (events.js:71)
    at Emitter.fire (events.js:135)
    at closeHandler (main.js:221)
    at CallbackList.invoke (events.js:71)
    at Emitter.fire (events.js:135)
    at WebSocketMessageReader.AbstractMessageReader.fireClose (messageReader.js:135)
    at WebSocketMessageReader.fireClose (reader.ts:72)
    at reader.ts:31
```

**Comment by kittaakos** [comment]
> I have bundled it into an AppImage, maybe that is the problem.

No. Same with `deb`.

**Comment by kittaakos** [comment]
> It does not start on Ubuntu either.

Was due to the missing Java on the system. Follow-up #6.

**Comment by kittaakos** [comment]
This issue can be consistently reproduced on Windows. Steps:
 - Install Yangster from the installer.
 - Start the application.
 - Select a WS.
 - Create a `.yang` file.

The problem never occurs in the second or any consecutive startups.

**Comment by kittaakos** [comment]
I cannot reproduce this anymore on Windows. I have tried several scenarios, with fresh installations, did not fail. I am closing this. We can reopen this ticket later if there is a reproducible setup which consistently fail.

**Comment by kittaakos** [comment]
It still happens. I have the feeling it depends on the number of the files in the WS.
