### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by kousikan** [theia-ide/yangster-electron#30]
Tried this command

git clone https://github.com/theia-ide/yangster-electron.git \
&& cd yangster-electron \
&& yarn \
&& yarn build \
&& yarn package

Failed with the following error message.
.
.
.
[2/4] 🚚  Fetching packages...
warning monaco-languageclient@0.10.2: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.3.0-next.9: The engine "vscode" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning "@theia/git > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@theia/git > @theia/scm > react-autosize-textarea@7.0.0" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "theia-yang-extension > yang-sprotty > sprotty > snabbdom-virtualize@0.7.0" has incorrect peer dependency "snabbdom@~0.6.6".
warning "@theia/cli > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "@theia/cli > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "@theia/cli > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
[1/10] ⠠ nsfw
[6/10] ⠠ find-git-repositories
[3/10] ⠠ @theia/node-pty
[4/10] ⠠ drivelist
error /Users/kousikan.veeramuthu/Downloads/yangster-electron/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: /Users/kousikan.veeramuthu/Downloads/yangster-electron/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 403
    at ClientRequest.https.get.response (/Users/kousikan.veeramuthu/Downloads/yangster-electron/node_modules/vscode-ripgrep/lib/download.js:106:24)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:193:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
    at TLSSocket.socketOnData (_http_client.js:447:22)
    at TLSSocket.emit (events.js:193:13)

**Comment by gituser9** [comment]
Also fail with node 13


yarn install v1.22.4
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning @theia/core > @theia/application-package > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @theia/core > react-virtualized > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @theia/editor > @theia/languages > @theia/workspace > @theia/filesystem > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
warning @theia/git > dugite-extra > dugite-no-gpl > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @theia/git > @theia/scm > @types/p-debounce@1.0.1: This is a stub types definition. p-debounce provides its own type definitions, so you do not need this installed.
warning theia-yang-extension > theia-sprotty > sprotty > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/cli > mocha > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning @theia/cli > @theia/application-manager > less > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > recast > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @theia/cli > @theia/application-manager > electron-rebuild > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @theia/cli > @theia/application-manager > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning electron-builder > electron-download-tf > nugget > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
warning monaco-languageclient@0.10.2: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.3.0-next.9: The engine "vscode" appears to be invalid.
error dugite-extra@0.1.12: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <12". Got "13.12.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by cedkim** [comment]
I'm also experiencing this issue on my own repo.

```
error /Users/runner/work/desktop/desktop/node_modules/vscode-ripgrep: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /Users/runner/work/desktop/desktop/node_modules/vscode-ripgrep
Output:
Finding release for v12.1.1
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v12.1.1
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 403
    at ClientRequest.https.get.response (/Users/runner/work/desktop/desktop/node_modules/vscode-ripgrep/lib/download.js:127:24)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:451:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
```

**Comment by cedkim** [comment]
This looks like it may be related to #25. However this looks a little different.

**Comment by duncdrum** [comment]
see https://github.com/theia-ide/dugite-extra/pull/49
